// LVGL UI: background, bubble indicator, and numeric readout.
#include "ui.h"
#include "lvgl.h"

#include <stdio.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>

#include "esp_log.h"
#include "esp_timer.h"
#include "nvs.h"
#include "nvs_flash.h"
#include "audio_mgr.h"
#include "board.h"

// Image generated by LVGL image converter (.c/.h)
#include "main_ui_bg.h"
#include "splash_screen.h"

// Prefer the custom digit font if it exists; fall back to built-in fonts.
#ifdef __has_include
    #if __has_include("ds_digit_36.h")
        #include "ds_digit_36.h"
        #define FONT_RAW (&ds_digit_36)
    #else
        #define FONT_RAW FONT_BIG
    #endif
#else
    #define FONT_RAW FONT_BIG
#endif

static const char *TAG = "ui";

// ---- LVGL objects ----
static lv_obj_t *s_bg_img       = NULL;
static lv_obj_t *s_label_status = NULL;
static lv_obj_t *s_dot_center   = NULL;
static lv_obj_t *s_raw_box      = NULL;
static lv_obj_t *s_splash_img   = NULL;
static lv_obj_t *s_label_raw    = NULL;
static lv_obj_t *s_zero_hold_arc = NULL;
static lv_obj_t *s_zero_hold_label = NULL;
static lv_obj_t *s_sound_btn    = NULL;
static lv_obj_t *s_sound_label  = NULL;
static lv_obj_t *s_sound_overlay = NULL;
static lv_obj_t *s_sound_panel  = NULL;
static lv_obj_t *s_sound_slider = NULL;
static lv_timer_t *s_sound_hide_timer = NULL;
static lv_timer_t *s_status_hide_timer = NULL;
static lv_timer_t *s_zero_done_timer = NULL;
static bool s_zero_hold_active = false;

// Last raw angles received from IMU (before applying offsets)
static float s_last_raw_roll  = 0.0f;
static float s_last_raw_pitch = 0.0f;

// Zero offsets loaded/saved in NVS
static float s_roll0  = 0.0f;
static float s_pitch0 = 0.0f;

#define SPLASH_DURATION_MS 5000
#define SOUND_PANEL_AUTOHIDE_MS 4500
#define STATUS_TOAST_MS 1400
#define ZERO_HOLD_MS 1000
#define ZERO_DONE_SHOW_MS 600

// Bubble geometry / behavior
#define DOT_SIZE       24

// Degrees -> pixels mapping (bubble travel)
#define MAX_DEG_X      20.0f
#define MAX_DEG_Y      23.0f

// Map travel radius (tweak if your graphic's circle radius differs)
#define MAX_PX         110.0f

// "Level" thresholds
#define LEVEL_GOOD_DEG 0.5f
#define LEVEL_OK_DEG   1.5f

// Clamp display range (deg)
#define ROLL_CLAMP_DEG  20.0f
#define PITCH_CLAMP_DEG 23.0f

// NVS
#define NVS_NS         "leveler"
#define NVS_KEY_ROLL0  "roll0_md"   // milli-degrees, int32
#define NVS_KEY_PITCH0 "pitch0_md"  // milli-degrees, int32
#define NVS_KEY_MUTE   "aud_muted"  // u8 0/1
#define NVS_KEY_VOL    "aud_vol"    // u8 0-100

// Background (true dark behind image edges, if any)
#define BG_COLOR       0x000000

// Raw readout box (bottom black box in background image)
#define RAW_BOX_X      44
#define RAW_BOX_Y      377
#define RAW_BOX_W      280
#define RAW_BOX_H      60
#define RAW_TEXT_Y_OFFSET 6
#define RAW_STATUS_GAP 8

// UI layout (tweak to match the new background art)
#define CENTER_CX      184
#define CENTER_CY      172
#define CENTER_R       110

// Fonts (enable these in LVGL config if not already)
#if LV_FONT_MONTSERRAT_28
#define FONT_TITLE   &lv_font_montserrat_28
#else
#define FONT_TITLE   LV_FONT_DEFAULT
#endif

#if LV_FONT_MONTSERRAT_24
#define FONT_BIG     &lv_font_montserrat_24
#else
#define FONT_BIG     LV_FONT_DEFAULT
#endif

#if LV_FONT_MONTSERRAT_18
#define FONT_MED     &lv_font_montserrat_18
#else
#define FONT_MED     LV_FONT_DEFAULT
#endif

// Basic clamp used by UI-only mapping.
static float clampf(float v, float lo, float hi)
{
    if (v < lo) return lo;
    if (v > hi) return hi;
    return v;
}

static int32_t deg_to_mdeg(float deg) { return (int32_t)lrintf(deg * 1000.0f); }
static float   mdeg_to_deg(int32_t mdeg) { return ((float)mdeg) / 1000.0f; }

// Load persisted zero offsets from NVS.
static void nvs_load_offsets(void)
{
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_LOGW(TAG, "NVS init needs erase (%s), erasing", esp_err_to_name(err));
        ESP_ERROR_CHECK(nvs_flash_erase());
        ESP_ERROR_CHECK(nvs_flash_init());
    } else if (err != ESP_OK) {
        ESP_LOGW(TAG, "NVS init failed (%s) - offsets won't persist", esp_err_to_name(err));
        return;
    }

    nvs_handle_t h;
    err = nvs_open(NVS_NS, NVS_READONLY, &h);
    if (err != ESP_OK) {
        ESP_LOGI(TAG, "NVS namespace not found yet; using 0 offsets");
        return;
    }

    int32_t r0 = 0, p0 = 0;
    esp_err_t er = nvs_get_i32(h, NVS_KEY_ROLL0, &r0);
    esp_err_t ep = nvs_get_i32(h, NVS_KEY_PITCH0, &p0);
    nvs_close(h);

    if (er == ESP_OK) s_roll0  = mdeg_to_deg(r0);
    if (ep == ESP_OK) s_pitch0 = mdeg_to_deg(p0);

    ESP_LOGI(TAG, "Loaded offsets: roll0=%.3f pitch0=%.3f", s_roll0, s_pitch0);
}

// Save current zero offsets to NVS.
static void nvs_save_offsets(void)
{
    nvs_handle_t h;
    esp_err_t err = nvs_open(NVS_NS, NVS_READWRITE, &h);
    if (err != ESP_OK) {
        ESP_LOGW(TAG, "NVS open failed (%s) - offsets won't persist", esp_err_to_name(err));
        return;
    }

    int32_t r0 = deg_to_mdeg(s_roll0);
    int32_t p0 = deg_to_mdeg(s_pitch0);

    err = nvs_set_i32(h, NVS_KEY_ROLL0, r0);
    if (err != ESP_OK) ESP_LOGW(TAG, "nvs_set_i32 roll failed: %s", esp_err_to_name(err));

    err = nvs_set_i32(h, NVS_KEY_PITCH0, p0);
    if (err != ESP_OK) ESP_LOGW(TAG, "nvs_set_i32 pitch failed: %s", esp_err_to_name(err));

    err = nvs_commit(h);
    if (err != ESP_OK) ESP_LOGW(TAG, "nvs_commit failed: %s", esp_err_to_name(err));

    nvs_close(h);

    ESP_LOGI(TAG, "Saved offsets: roll0=%.3f pitch0=%.3f", s_roll0, s_pitch0);
}

// Load persisted sound preferences (mute + volume).
static void nvs_load_audio_prefs(void)
{
    nvs_handle_t h;
    esp_err_t err = nvs_open(NVS_NS, NVS_READONLY, &h);
    if (err != ESP_OK) {
        return;
    }

    uint8_t muted_u8 = 0;
    uint8_t vol_u8 = 45;
    bool has_mute = (nvs_get_u8(h, NVS_KEY_MUTE, &muted_u8) == ESP_OK);
    bool has_vol = (nvs_get_u8(h, NVS_KEY_VOL, &vol_u8) == ESP_OK);
    nvs_close(h);

    if (has_vol) {
        audio_mgr_set_volume((int)vol_u8);
    }
    if (has_mute) {
        audio_mgr_set_muted(muted_u8 != 0);
    }
}

// Save mute/volume so sound behavior survives reboot.
static void nvs_save_audio_prefs(void)
{
    nvs_handle_t h;
    esp_err_t err = nvs_open(NVS_NS, NVS_READWRITE, &h);
    if (err != ESP_OK) {
        ESP_LOGW(TAG, "NVS open failed (%s) - audio prefs won't persist", esp_err_to_name(err));
        return;
    }

    uint8_t muted_u8 = audio_mgr_is_muted() ? 1 : 0;
    int vol = audio_mgr_get_volume();
    if (vol < 0) vol = 0;
    if (vol > 100) vol = 100;
    uint8_t vol_u8 = (uint8_t)vol;

    err = nvs_set_u8(h, NVS_KEY_MUTE, muted_u8);
    if (err != ESP_OK) ESP_LOGW(TAG, "nvs_set_u8 mute failed: %s", esp_err_to_name(err));
    err = nvs_set_u8(h, NVS_KEY_VOL, vol_u8);
    if (err != ESP_OK) ESP_LOGW(TAG, "nvs_set_u8 volume failed: %s", esp_err_to_name(err));
    err = nvs_commit(h);
    if (err != ESP_OK) ESP_LOGW(TAG, "nvs_commit audio failed: %s", esp_err_to_name(err));
    nvs_close(h);
}

void ui_apply_offsets(float raw_roll_deg, float raw_pitch_deg, float *adj_roll_deg, float *adj_pitch_deg)
{
    if (adj_roll_deg) {
        *adj_roll_deg = raw_roll_deg - s_roll0;
    }
    if (adj_pitch_deg) {
        *adj_pitch_deg = raw_pitch_deg - s_pitch0;
    }
}

// Color the bubble based on proximity to level.
static void set_dot_color(float roll_deg, float pitch_deg)
{
    float aroll  = fabsf(roll_deg);
    float apitch = fabsf(pitch_deg);

    lv_color_t c;
    if (aroll <= LEVEL_GOOD_DEG && apitch <= LEVEL_GOOD_DEG) {
        c = lv_color_hex(0x39D98A); // green
    } else if (aroll <= LEVEL_OK_DEG && apitch <= LEVEL_OK_DEG) {
        c = lv_color_hex(0xF2C94C); // amber
    } else {
        c = lv_color_hex(0xEB5757); // red
    }

    if (s_dot_center) lv_obj_set_style_bg_color(s_dot_center, c, 0);
}

static void status_hide_timer_cb(lv_timer_t *t)
{
    // Keep timer allocated; use pause/resume instead of one-shot auto-delete.
    lv_timer_pause(t);
    if (s_label_status) lv_obj_add_flag(s_label_status, LV_OBJ_FLAG_HIDDEN);
}

// Small transient status message near the bottom readout.
static void ui_status_toast(const char *msg, lv_color_t color)
{
    if (!s_label_status || !msg) return;
    lv_obj_set_style_text_color(s_label_status, color, 0);
    lv_label_set_text(s_label_status, msg);
    lv_obj_clear_flag(s_label_status, LV_OBJ_FLAG_HIDDEN);

    if (!s_status_hide_timer) {
        s_status_hide_timer = lv_timer_create(status_hide_timer_cb, STATUS_TOAST_MS, NULL);
        if (s_status_hide_timer) lv_timer_pause(s_status_hide_timer);
    } else {
        lv_timer_set_period(s_status_hide_timer, STATUS_TOAST_MS);
    }
    if (s_status_hide_timer) {
        lv_timer_resume(s_status_hide_timer);
        lv_timer_reset(s_status_hide_timer);
    }
}

static void sound_hide_timer_cb(lv_timer_t *t)
{
    // Keep timer allocated; use pause/resume instead of one-shot auto-delete.
    lv_timer_pause(t);
    if (s_sound_panel) lv_obj_add_flag(s_sound_panel, LV_OBJ_FLAG_HIDDEN);
    if (s_sound_overlay) lv_obj_add_flag(s_sound_overlay, LV_OBJ_FLAG_HIDDEN);
}

static void sound_panel_show(void)
{
    if (s_sound_overlay) {
        lv_obj_clear_flag(s_sound_overlay, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_foreground(s_sound_overlay);
    }
    if (s_sound_panel) {
        lv_obj_clear_flag(s_sound_panel, LV_OBJ_FLAG_HIDDEN);
        lv_obj_move_foreground(s_sound_panel);
    }
    if (s_sound_btn) lv_obj_move_foreground(s_sound_btn);
    if (s_sound_hide_timer) {
        lv_timer_set_period(s_sound_hide_timer, SOUND_PANEL_AUTOHIDE_MS);
        lv_timer_resume(s_sound_hide_timer);
        lv_timer_reset(s_sound_hide_timer);
    }
}

static void sound_panel_hide(void)
{
    if (s_sound_panel) lv_obj_add_flag(s_sound_panel, LV_OBJ_FLAG_HIDDEN);
    if (s_sound_overlay) lv_obj_add_flag(s_sound_overlay, LV_OBJ_FLAG_HIDDEN);
    if (s_sound_hide_timer) lv_timer_pause(s_sound_hide_timer);
}

static void zero_progress_set(float frac)
{
    if (!s_zero_hold_arc) return;
    if (frac < 0.0f) frac = 0.0f;
    if (frac > 1.0f) frac = 1.0f;
    lv_arc_set_value(s_zero_hold_arc, (int32_t)lrintf(frac * 100.0f));
    lv_obj_clear_flag(s_zero_hold_arc, LV_OBJ_FLAG_HIDDEN);
    if (s_zero_hold_label) lv_obj_clear_flag(s_zero_hold_label, LV_OBJ_FLAG_HIDDEN);
}

static void zero_progress_hide(void)
{
    if (s_zero_hold_arc) lv_obj_add_flag(s_zero_hold_arc, LV_OBJ_FLAG_HIDDEN);
    if (s_zero_hold_label) lv_obj_add_flag(s_zero_hold_label, LV_OBJ_FLAG_HIDDEN);
}

static void zero_done_timer_cb(lv_timer_t *t)
{
    lv_timer_pause(t);
    s_zero_hold_active = false;
    zero_progress_hide();
    if (s_zero_hold_label) lv_label_set_text(s_zero_hold_label, "Hold\nto Zero");
}

void ui_zero_current(void)
{
    s_roll0  = s_last_raw_roll;
    s_pitch0 = s_last_raw_pitch;

    nvs_save_offsets();
    ui_status_toast("Zeroed", lv_color_hex(0x39D98A));

    ui_set_angles(s_last_raw_roll, s_last_raw_pitch);
}

void ui_zero_hold_progress(float frac)
{
    if (frac < 0.0f) frac = 0.0f;
    if (frac > 1.0f) frac = 1.0f;
    if (!s_zero_hold_active) {
        s_zero_hold_active = true;
        ui_status_toast("Hold to zero", lv_color_hex(0xF2C94C));
    }
    if (s_zero_hold_label) lv_label_set_text(s_zero_hold_label, "Hold\nto Zero");
    zero_progress_set(frac);
}

void ui_zero_hold_cancel(void)
{
    s_zero_hold_active = false;
    zero_progress_hide();
    if (s_zero_hold_label) lv_label_set_text(s_zero_hold_label, "Hold\nto Zero");
}

void ui_zero_hold_complete(void)
{
    s_zero_hold_active = true;
    if (s_zero_hold_label) lv_label_set_text(s_zero_hold_label, "Zeroed");
    zero_progress_set(1.0f);
    if (!s_zero_done_timer) {
        s_zero_done_timer = lv_timer_create(zero_done_timer_cb, ZERO_DONE_SHOW_MS, NULL);
        if (s_zero_done_timer) lv_timer_pause(s_zero_done_timer);
    }
    if (s_zero_done_timer) {
        lv_timer_set_period(s_zero_done_timer, ZERO_DONE_SHOW_MS);
        lv_timer_resume(s_zero_done_timer);
        lv_timer_reset(s_zero_done_timer);
    }
}

// Sync the icon with current mute state.
static void sound_refresh_icon(void)
{
    if (!s_sound_label) return;
    lv_label_set_text(s_sound_label, audio_mgr_is_muted() ? LV_SYMBOL_MUTE : LV_SYMBOL_VOLUME_MAX);
}

// Volume slider callback.
static void sound_slider_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (!s_sound_slider) return;

    if (code == LV_EVENT_VALUE_CHANGED) {
        int vol = lv_slider_get_value(s_sound_slider);
        audio_mgr_set_volume(vol);
        nvs_save_audio_prefs();
        if (s_sound_hide_timer) lv_timer_reset(s_sound_hide_timer);
        return;
    }

    if (code == LV_EVENT_RELEASED) {
        char msg[24];
        snprintf(msg, sizeof(msg), "Volume %d%%", audio_mgr_get_volume());
        ui_status_toast(msg, lv_color_hex(0xE9EDF2));
        return;
    }
}

// Overlay tap closes the volume popover.
static void sound_overlay_event_cb(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    sound_panel_hide();
}

// Sound toggle button callback.
static void sound_btn_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);

    if (code == LV_EVENT_LONG_PRESSED) {
        if (s_sound_panel) {
            // Long-press toggles the volume panel so it does not vanish mid-adjustment.
            if (lv_obj_has_flag(s_sound_panel, LV_OBJ_FLAG_HIDDEN)) {
                sound_panel_show();
                if (s_sound_slider) {
                    lv_slider_set_value(s_sound_slider, audio_mgr_get_volume(), LV_ANIM_OFF);
                }
            } else {
                sound_panel_hide();
            }
        }
        return;
    }

    if (code == LV_EVENT_SHORT_CLICKED) {
        ui_toggle_mute();
        return;
    }
}

void ui_toggle_mute(void)
{
    bool will_mute = !audio_mgr_is_muted();
    audio_mgr_set_muted(will_mute);
    nvs_save_audio_prefs();
    sound_refresh_icon();
    ui_status_toast(will_mute ? "Sound off" : "Sound on", lv_color_hex(0xE9EDF2));
}

void ui_toggle_mute_runtime(void)
{
    bool will_mute = !audio_mgr_is_muted();
    audio_mgr_set_muted(will_mute);
    sound_refresh_icon();
    ui_status_toast(will_mute ? "Sound off" : "Sound on", lv_color_hex(0xE9EDF2));
}

// One-shot timer to hide the splash screen.
static void splash_timer_cb(lv_timer_t *t)
{
    (void)t;
    if (s_splash_img) {
        lv_obj_del(s_splash_img);
        s_splash_img = NULL;
    }
    // Beeps start only after splash is dismissed.
    audio_mgr_set_enabled(true);
}

// Show splash for a fixed duration.
void ui_show_splash(uint32_t duration_ms)
{
    lv_obj_t *scr = lv_screen_active();

    if (s_splash_img) {
        lv_obj_del(s_splash_img);
        s_splash_img = NULL;
    }

    s_splash_img = lv_image_create(scr);
    lv_image_set_src(s_splash_img, &splash_screen);
    lv_obj_align(s_splash_img, LV_ALIGN_CENTER, 0, 0);
    lv_obj_clear_flag(s_splash_img, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_move_foreground(s_splash_img);

    lv_timer_t *timer = lv_timer_create(splash_timer_cb, duration_ms, NULL);
    if (timer) {
        lv_timer_set_repeat_count(timer, 1);
    }
}

// Show a persistent orange banner at the top of the screen warning the user
// that the previous OTA failed and the firmware was rolled back.
// Must be called with the LVGL lock held, after ui_init().
void ui_show_rollback_warning(void)
{
    lv_obj_t *scr = lv_screen_active();

    lv_obj_t *bar = lv_obj_create(scr);
    lv_obj_set_size(bar, LCD_H_RES, 30);
    lv_obj_set_pos(bar, 0, 0);
    lv_obj_remove_style_all(bar);
    lv_obj_set_style_bg_opa(bar, LV_OPA_COVER, 0);
    lv_obj_set_style_bg_color(bar, lv_color_hex(0xC0510A), 0);  // dark orange
    lv_obj_clear_flag(bar, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_clear_flag(bar, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_move_foreground(bar);

    lv_obj_t *lbl = lv_label_create(bar);
    lv_label_set_text(lbl, LV_SYMBOL_WARNING " OTA rollback \xe2\x80\x94 update failed, prior firmware restored");
    lv_obj_set_style_text_color(lbl, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_text_font(lbl, LV_FONT_DEFAULT, 0);
    lv_obj_align(lbl, LV_ALIGN_CENTER, 0, 0);

    ESP_LOGW("ui", "rollback warning banner shown");
}

// Build the LVGL scene graph and initialize display values.
void ui_init(void)
{
    nvs_load_offsets();
    nvs_load_audio_prefs();
    audio_mgr_set_enabled(false);

    lv_obj_t *scr = lv_screen_active();

    // Remove any theme styling (prevents weird background colors)
    lv_obj_remove_style_all(scr);

    // Base background (in case image doesn't cover perfectly)
    lv_obj_set_style_bg_color(scr, lv_color_hex(BG_COLOR), 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);

    // ---- FULL SCREEN BACKGROUND IMAGE ----
    s_bg_img = lv_image_create(scr);
    lv_image_set_src(s_bg_img, &main_ui_bg);
    lv_obj_align(s_bg_img, LV_ALIGN_CENTER, 0, 0);
    lv_obj_clear_flag(s_bg_img, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_move_background(s_bg_img);

    // Status label (hidden until used)
    s_label_status = lv_label_create(scr);
    lv_obj_set_style_text_font(s_label_status, FONT_MED, 0);
    lv_obj_set_style_text_color(s_label_status, lv_color_hex(0x39D98A), 0);
    lv_label_set_text(s_label_status, "");
    lv_obj_align(s_label_status, LV_ALIGN_TOP_LEFT, RAW_BOX_X, RAW_BOX_Y - RAW_STATUS_GAP - 18);
    lv_obj_add_flag(s_label_status, LV_OBJ_FLAG_HIDDEN);

    // ---- Raw readout (bottom black box) ----
    s_raw_box = lv_obj_create(scr);
    lv_obj_set_size(s_raw_box, RAW_BOX_W, RAW_BOX_H);
    lv_obj_set_pos(s_raw_box, RAW_BOX_X, RAW_BOX_Y);
    lv_obj_remove_style_all(s_raw_box);
    lv_obj_set_style_bg_opa(s_raw_box, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_opa(s_raw_box, LV_OPA_TRANSP, 0);
    lv_obj_clear_flag(s_raw_box, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_clear_flag(s_raw_box, LV_OBJ_FLAG_CLICKABLE);

    // Center radial hold-to-zero progress.
    s_zero_hold_arc = lv_arc_create(scr);
    lv_obj_set_size(s_zero_hold_arc, 138, 138);
    lv_obj_align(s_zero_hold_arc, LV_ALIGN_CENTER, 0, 0);
    lv_arc_set_range(s_zero_hold_arc, 0, 100);
    lv_arc_set_value(s_zero_hold_arc, 0);
    lv_arc_set_rotation(s_zero_hold_arc, 270); // 0% at 12 o'clock.
    lv_arc_set_bg_angles(s_zero_hold_arc, 0, 360);
    lv_obj_set_style_arc_width(s_zero_hold_arc, 10, LV_PART_MAIN);
    lv_obj_set_style_arc_color(s_zero_hold_arc, lv_color_hex(0x2E3440), LV_PART_MAIN);
    lv_obj_set_style_arc_width(s_zero_hold_arc, 12, LV_PART_INDICATOR);
    lv_obj_set_style_arc_color(s_zero_hold_arc, lv_color_hex(0x39D98A), LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(s_zero_hold_arc, true, LV_PART_INDICATOR);
    lv_obj_add_flag(s_zero_hold_arc, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(s_zero_hold_arc, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(s_zero_hold_arc, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(s_zero_hold_arc, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_set_style_bg_opa(s_zero_hold_arc, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_opa(s_zero_hold_arc, LV_OPA_TRANSP, 0);
    lv_obj_remove_style(s_zero_hold_arc, NULL, LV_PART_KNOB);

    s_zero_hold_label = lv_label_create(scr);
    lv_obj_set_style_text_font(s_zero_hold_label, FONT_BIG, 0);
    lv_obj_set_style_text_color(s_zero_hold_label, lv_color_hex(0x12151A), 0);
    lv_label_set_text(s_zero_hold_label, "Hold\nto Zero");
    lv_obj_set_style_text_align(s_zero_hold_label, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_align_to(s_zero_hold_label, s_zero_hold_arc, LV_ALIGN_CENTER, 0, 0);
    lv_obj_add_flag(s_zero_hold_label, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(s_zero_hold_label, LV_OBJ_FLAG_CLICKABLE);

    s_label_raw = lv_label_create(scr);
    lv_obj_set_style_text_font(s_label_raw, FONT_RAW, 0);
    lv_obj_set_style_text_color(s_label_raw, lv_color_hex(0xE5E5E5), 0);
    lv_obj_set_size(s_label_raw, RAW_BOX_W, RAW_BOX_H);
    lv_obj_set_style_text_align(s_label_raw, LV_TEXT_ALIGN_CENTER, 0);
    lv_label_set_text(s_label_raw, "R:0.00in  P:0.00in");
    lv_obj_set_pos(s_label_raw, RAW_BOX_X, RAW_BOX_Y + RAW_TEXT_Y_OFFSET + 4);
    // Keep label passive; zeroing is handled by side button long-press now.
    lv_obj_clear_flag(s_label_raw, LV_OBJ_FLAG_CLICKABLE);

    // Sound toggle in top-right corner.
    s_sound_btn = lv_button_create(scr);
    // Slightly larger target so the sound control is easier to hit.
    lv_obj_set_size(s_sound_btn, 60, 52);
    lv_obj_align(s_sound_btn, LV_ALIGN_TOP_RIGHT, -10, 10);
    lv_obj_set_style_radius(s_sound_btn, 12, 0);
    lv_obj_set_style_bg_color(s_sound_btn, lv_color_hex(0x12151A), 0);
    lv_obj_set_style_border_color(s_sound_btn, lv_color_hex(0x2E3440), 0);
    lv_obj_set_style_border_width(s_sound_btn, 1, 0);
    lv_obj_set_ext_click_area(s_sound_btn, 14);
    lv_obj_add_event_cb(s_sound_btn, sound_btn_event_cb, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_event_cb(s_sound_btn, sound_btn_event_cb, LV_EVENT_LONG_PRESSED, NULL);

    s_sound_label = lv_label_create(s_sound_btn);
    sound_refresh_icon();
    lv_obj_set_style_text_font(s_sound_label, FONT_BIG, 0);
    lv_obj_set_style_text_color(s_sound_label, lv_color_hex(0xE9EDF2), 0);
    lv_obj_center(s_sound_label);

    // Full-screen transparent overlay to support "tap outside to close".
    s_sound_overlay = lv_obj_create(scr);
    lv_obj_remove_style_all(s_sound_overlay);
    lv_obj_set_size(s_sound_overlay, lv_pct(100), lv_pct(100));
    lv_obj_align(s_sound_overlay, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_bg_opa(s_sound_overlay, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_opa(s_sound_overlay, LV_OPA_TRANSP, 0);
    lv_obj_add_flag(s_sound_overlay, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(s_sound_overlay, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_event_cb(s_sound_overlay, sound_overlay_event_cb, LV_EVENT_CLICKED, NULL);

    // Hidden volume popover shown by long-pressing the sound button.
    s_sound_panel = lv_obj_create(scr);
    lv_obj_set_size(s_sound_panel, 54, 178);
    lv_obj_align_to(s_sound_panel, s_sound_btn, LV_ALIGN_OUT_BOTTOM_MID, 0, 8);
    lv_obj_set_style_radius(s_sound_panel, 12, 0);
    lv_obj_set_style_bg_color(s_sound_panel, lv_color_hex(0x12151A), 0);
    lv_obj_set_style_border_color(s_sound_panel, lv_color_hex(0x2E3440), 0);
    lv_obj_set_style_border_width(s_sound_panel, 1, 0);
    lv_obj_clear_flag(s_sound_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(s_sound_panel, LV_OBJ_FLAG_HIDDEN);

    s_sound_slider = lv_slider_create(s_sound_panel);
    lv_obj_set_size(s_sound_slider, 18, 128);
    lv_obj_center(s_sound_slider);
    lv_slider_set_range(s_sound_slider, 0, 100);
    lv_slider_set_value(s_sound_slider, audio_mgr_get_volume(), LV_ANIM_OFF);
    lv_obj_add_event_cb(s_sound_slider, sound_slider_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(s_sound_slider, sound_slider_event_cb, LV_EVENT_RELEASED, NULL);

    // Auto-hide timer keeps the slider available during adjustment but closes when idle.
    s_sound_hide_timer = lv_timer_create(sound_hide_timer_cb, SOUND_PANEL_AUTOHIDE_MS, NULL);
    if (s_sound_hide_timer) {
        lv_timer_pause(s_sound_hide_timer);
    }

    // ---- Bubble dots ----
    s_dot_center = lv_obj_create(scr);
    lv_obj_set_size(s_dot_center, DOT_SIZE, DOT_SIZE);
    lv_obj_set_style_radius(s_dot_center, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(s_dot_center, lv_color_hex(0xEB5757), 0); // start red
    lv_obj_set_style_bg_opa(s_dot_center, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(s_dot_center, 0, 0);
    lv_obj_clear_flag(s_dot_center, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_align(s_dot_center, LV_ALIGN_TOP_LEFT, CENTER_CX - (DOT_SIZE / 2), CENTER_CY - (DOT_SIZE / 2));

    // Ensure dot and text are above background
    lv_obj_move_foreground(s_dot_center);
    lv_obj_move_foreground(s_label_status);
    lv_obj_move_foreground(s_raw_box);
    lv_obj_move_foreground(s_label_raw);
    lv_obj_move_foreground(s_zero_hold_arc);
    lv_obj_move_foreground(s_zero_hold_label);
    lv_obj_move_foreground(s_sound_overlay);
    lv_obj_move_foreground(s_sound_btn);
    lv_obj_move_foreground(s_sound_panel);

    // Initialize display values
    ui_set_angles(0.0f, 0.0f);
    ui_set_inches(0.0f, 0.0f);

    ui_show_splash(SPLASH_DURATION_MS);
}

// Update the bubble position and status colors from raw IMU angles.
void ui_set_angles(float roll_deg_raw, float pitch_deg_raw)
{
    if (!s_label_raw || !s_dot_center) return;

    s_last_raw_roll  = roll_deg_raw;
    s_last_raw_pitch = pitch_deg_raw;

    // Apply offsets + clamp
    float roll_deg  = roll_deg_raw  - s_roll0;
    float pitch_deg = pitch_deg_raw - s_pitch0;
    roll_deg = clampf(roll_deg, -ROLL_CLAMP_DEG, ROLL_CLAMP_DEG);
    pitch_deg = clampf(pitch_deg, -PITCH_CLAMP_DEG, PITCH_CLAMP_DEG);

    // Map degrees to pixels
    float rx = clampf(roll_deg  / MAX_DEG_X, -1.0f, 1.0f);
    float py = clampf(pitch_deg / MAX_DEG_Y, -1.0f, 1.0f);

    float dx = rx * CENTER_R;
    float dy = py * CENTER_R;

    // Circular clamp so it stays inside a circle
    float r = sqrtf(dx * dx + dy * dy);
    if (r > CENTER_R && r > 0.0001f) {
        float s = CENTER_R / r;
        dx *= s;
        dy *= s;
    }

    // Move center dot relative to center circle
    int center_x = CENTER_CX + (int)lrintf(dx) - (DOT_SIZE / 2);
    int center_y = CENTER_CY + (int)lrintf(dy) - (DOT_SIZE / 2);
    lv_obj_align(s_dot_center, LV_ALIGN_TOP_LEFT, center_x, center_y);

    set_dot_color(roll_deg, pitch_deg);
}

// Update the numeric readout (inches).
void ui_set_inches(float roll_in, float pitch_in)
{
    if (!s_label_raw) return;
    char buf[48];
    snprintf(buf, sizeof(buf), "R:%.1f in  P:%.1f in", roll_in, pitch_in);
    lv_label_set_text(s_label_raw, buf);
}
